---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-prod
  namespace: prod
spec:
  interval: 1m0s
  path: ./artifacts/kustomize/overlays/prod
  prune: true
  targetNamespace: prod
  sourceRef:
    kind: GitRepository
    name: nginx-prod
    namespace: prod