---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-dev
  namespace: dev
spec:
  interval: 1m0s
  path: ./artifacts/kustomize/overlays/dev
  prune: true
  targetNamespace: dev
  sourceRef:
    kind: GitRepository
    name: nginx-dev
    namespace: dev