---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: webapp
  namespace: apps
spec:
  interval: 1m0s
  path: ./artifacts/python/example-app/k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp